// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveSystemFrontLeft = NULL;
SpeedController* RobotMap::driveSystemFrontRight = NULL;
SpeedController* RobotMap::driveSystemRearLeft = NULL;
SpeedController* RobotMap::driveSystemRearRight = NULL;
RobotDrive* RobotMap::driveSystemRobotDrive41 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveSystemFrontLeft = new Talon(0);
	lw->AddActuator("DriveSystem", "FrontLeft", (Talon*) driveSystemFrontLeft);
	
	driveSystemFrontRight = new Talon(1);
	lw->AddActuator("DriveSystem", "FrontRight", (Talon*) driveSystemFrontRight);
	
	driveSystemRearLeft = new Talon(2);
	lw->AddActuator("DriveSystem", "RearLeft", (Talon*) driveSystemRearLeft);
	
	driveSystemRearRight = new Talon(3);
	lw->AddActuator("DriveSystem", "RearRight", (Talon*) driveSystemRearRight);
	
	driveSystemRobotDrive41 = new RobotDrive(driveSystemFrontLeft, driveSystemRearLeft,
              driveSystemFrontRight, driveSystemRearRight);
	
	driveSystemRobotDrive41->SetSafetyEnabled(true);
        driveSystemRobotDrive41->SetExpiration(0.1);
        driveSystemRobotDrive41->SetSensitivity(0.5);
        driveSystemRobotDrive41->SetMaxOutput(1.0);


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
